
project_id = "gjwwzygpxigmhxugftse"

[functions.generate-lesson-plan]
verify_jwt = true

[functions.ai-tutor-chat]
verify_jwt = true

[functions]
[functions.options]
apikey_env = "SUPABASE_SERVICE_ROLE_KEY"
