// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjwwzygpxigmhxugftse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdqd3d6eWdweGlnbWh4dWdmdHNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNzU4ODEsImV4cCI6MjA2MDg1MTg4MX0.LjcrZAxFdUI2i8PeNK5dNzy9n6JY-EwF4QEiyA8fSiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);